### ISSUE TITLE
MultipleServiceBindingsException thrown when trying to get destination.

### ISSUE THREAD

**Issue by akshat0496** [SAP/cloud-sdk-java#147]
Hi,

I have a CAP Java project deployed in Kyma environment in BTP. I want to use the Cloud SDK to access another BTP service using destinations. 

But when I try to get the destinations using : DestinationAccessor.getDestination("destination_name"), the cloud SDK is not even able to connect to the destination service instance. 
There are a total of 4 service bindings in my kyma environment, out of which there is only one for the destination service, still it complains that there are multiple.

Error Stack for MultipleServiceBindingsException:
```
Caused by: com.sap.cloud.sdk.cloudplatform.connectivity.exception.DestinationAccessException: Could not resolve destination to Destination Service on behalf of TECHNICAL_USER_CURRENT_TENANT.
        at com.sap.cloud.sdk.cloudplatform.connectivity.ScpCfDestinationServiceAdapter.lambda$prepareServiceDestinationComputation$0(ScpCfDestinationServiceAdapter.java:112) ~[cloudplatform-connectivity-scp-cf-4.19.0.jar:na]
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source) ~[na:na]
        at com.sap.cloud.sdk.cloudplatform.connectivity.ScpCfDestinationServiceAdapter.lambda$prepareServiceDestinationComputation$1(ScpCfDestinationServiceAdapter.java:100) ~[cloudplatform-connectivity-scp-cf-4.19.0.jar:na]
        at com.sap.cloud.sdk.cloudplatform.connectivity.ScpCfDestinationServiceAdapter.getConfigurationAsJsonInternal(ScpCfDestinationServiceAdapter.java:219) ~[cloudplatform-connectivity-scp-cf-4.19.0.jar:na]
        at com.sap.cloud.sdk.cloudplatform.connectivity.ScpCfDestinationServiceAdapter.getConfigurationAsJsonWithUserToken(ScpCfDestinationServiceAdapter.java:196) ~[cloudplatform-connectivity-scp-cf-4.19.0.jar:na]
        at com.sap.cloud.sdk.cloudplatform.connectivity.ScpCfDestinationLoader.lambda$loadAndParseDestination$0(ScpCfDestinationLoader.java:158) ~[cloudplatform-connectivity-scp-cf-4.19.0.jar:na]
        at com.sap.cloud.sdk.frameworks.resilience4j.Resilience4jDecorationStrategy.lambda$decorateCallable$2(Resilience4jDecorationStrategy.java:179) ~[resilience4j-4.19.0.jar:na]
        at io.github.resilience4j.bulkhead.Bulkhead.lambda$decorateCallable$4(Bulkhead.java:177) ~[resilience4j-bulkhead-1.7.1.jar:1.7.1]
        at com.sap.cloud.sdk.cloudplatform.thread.ThreadContextExecutor.call(ThreadContextExecutor.java:302) ~[cloudplatform-core-4.19.0.jar:na]
        at com.sap.cloud.sdk.cloudplatform.thread.ThreadContextExecutor.execute(ThreadContextExecutor.java:246) ~[cloudplatform-core-4.19.0.jar:na]
        ... 8 common frames omitted
Caused by: com.sap.cloud.sdk.cloudplatform.exception.MultipleServiceBindingsException: Having multiple Destination Service bindings is not supported.
        at com.sap.cloud.sdk.cloudplatform.connectivity.ScpCfDestinationServiceAdapter.getDestinationServiceBinding(ScpCfDestinationServiceAdapter.java:261) ~[cloudplatform-connectivity-scp-cf-4.19.0.jar:na]
        at com.sap.cloud.sdk.cloudplatform.connectivity.ScpCfDestinationServiceAdapter.lambda$prepareServiceDestinationComputation$0(ScpCfDestinationServiceAdapter.java:102) ~[cloudplatform-connectivity-scp-cf-4.19.0.jar:na]
        ... 17 common frames omitted
```

* SDK Version: 4.20.0

When I looked at the VCAP_SERVICES variable, I found that it has 2 duplicate bindings for the destination service instance.

Looking at the debug logs, I also noticed that first it is fetching the bindings from the /bindings path and then again from the VCAP_SERVICES, which results in a total of 8 bindings (4+4), even though there should only be total 4 bindings. 

<img width="968" alt="image" src="https://github.com/SAP/cloud-sdk-java/assets/8494160/365364e2-5f29-4a48-8c70-71b95508c36c">

Also when I do: kubectl get servicebindings, I can only see one binding for the destination service.

**Comment by newtork** [comment]
Interesting. What happens if you run the following code (e.g. once, during startup):
```java
DefaultServiceBindingAccessor.setInstance(new SapServiceOperatorServiceBindingIoAccessor());
```

This will disable `SapVcapServicesServiceBindingAccessor` from being executed. So **maybe** this solves the symptom.

If this works, we can investigate the unexpected duplication.

Kind regards
Alexander

**Comment by akshat0496** [comment]
Thanks for the idea. Actually, the DefaultServiceBindingAccessor did not work for me, but what did work was this:

`cloudPlatform = ScpCfCloudPlatform.getInstanceOrThrow();
cloudPlatform.setServiceBindingAccessor(new SapServiceOperatorServiceBindingIoAccessor());`

Also, I had to change the cloud-sdk version to 4.10.0

And now, in the debug logs, I can see that the VCAP_SERVICES is not being used to fetch the bindings. And the DestinationAccessor.getDestination() works fine.

**Comment by newtork** [comment]
Okay, good then.
Please keep in mind to always update dependencies :)
