### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.hc.client5.http.ssl.TlsSocketStrategy configuring a custom HttpClient in Spring Gateway

### ISSUE THREAD

**Issue by gsartori** [SAP/cloud-sdk-java#611]
## Issue Description
I'm getting the following exception configuring a custom `HttpClient` from a destination in Spring Gateway.

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestFactory' defined in class path resource [sap/SapDestinationHttpClientConfiguration.class]: Failed to instantiate [org.springframework.http.client.HttpComponentsClientHttpRequestFactory]: Factory method 'requestFactory' threw exception with message: org/apache/hc/client5/http/ssl/TlsSocketStrategy
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648) ~[spring-beans-6.1.13.jar:6.1.13]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:485) ~[spring-beans-6.1.13.jar:6.1.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1355) ~[spring-beans-6.1.13.jar:6.1.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185) ~[spring-beans-6.1.13.jar:6.1.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[spring-beans-6.1.13.jar:6.1.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.13.jar:6.1.13]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337) ~[spring-beans-6.1.13.jar:6.1.13]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.13.jar:6.1.13]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spring-beans-6.1.13.jar:6.1.13]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.13.jar:6.1.13]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.13.jar:6.1.13]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:971) ~[spring-context-6.1.13.jar:6.1.13]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:625) ~[spring-context-6.1.13.jar:6.1.13]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.3.4.jar:3.3.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.3.4.jar:3.3.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.3.4.jar:3.3.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) ~[spring-boot-3.3.4.jar:3.3.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363) ~[spring-boot-3.3.4.jar:3.3.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352) ~[spring-boot-3.3.4.jar:3.3.4]
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321) ~[groovy-4.0.23.jar:4.0.23]
	at sap.HttpclientApplication.main(HttpclientApplication.groovy:10) ~[main/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.http.client.HttpComponentsClientHttpRequestFactory]: Factory method 'requestFactory' threw exception with message: org/apache/hc/client5/http/ssl/TlsSocketStrategy
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:178) ~[spring-beans-6.1.13.jar:6.1.13]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:644) ~[spring-beans-6.1.13.jar:6.1.13]
	... 20 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/apache/hc/client5/http/ssl/TlsSocketStrategy
	at com.sap.cloud.sdk.cloudplatform.connectivity.ApacheHttpClient5FactoryBuilder.<init>(ApacheHttpClient5FactoryBuilder.java:23) ~[connectivity-apache-httpclient5-5.13.0.jar:na]
	at com.sap.cloud.sdk.cloudplatform.connectivity.ApacheHttpClient5Accessor.newDefaultFactory(ApacheHttpClient5Accessor.java:102) ~[connectivity-apache-httpclient5-5.13.0.jar:na]
	at com.sap.cloud.sdk.cloudplatform.connectivity.ApacheHttpClient5Accessor.<clinit>(ApacheHttpClient5Accessor.java:50) ~[connectivity-apache-httpclient5-5.13.0.jar:na]
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[na:na]
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155) ~[na:na]
	at java.base/java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:377) ~[na:na]
	at java.base/java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:374) ~[na:na]
	at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228) ~[na:na]
	at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210) ~[na:na]
	at java.base/java.lang.ClassValue.get(ClassValue.java:116) ~[na:na]
	at java.base/java.lang.invoke.DirectMethodHandle.checkInitialized(DirectMethodHandle.java:400) ~[na:na]
	at java.base/java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:388) ~[na:na]
	at java.base/java.lang.invoke.DirectMethodHandle.internalMemberNameEnsureInit(DirectMethodHandle.java:338) ~[na:na]
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321) ~[groovy-4.0.23.jar:4.0.23]
	at sap.SapDestinationHttpClientConfiguration.requestFactory(SapDestinationHttpClientConfiguration.groovy:17) ~[main/:na]
	at sap.SapDestinationHttpClientConfiguration$$SpringCGLIB$$0.CGLIB$requestFactory$3(<generated>) ~[main/:na]
	at sap.SapDestinationHttpClientConfiguration$$SpringCGLIB$$FastClass$$1.invoke(<generated>) ~[main/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258) ~[spring-core-6.1.13.jar:6.1.13]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:348) ~[spring-context-6.1.13.jar:6.1.13]
	at sap.SapDestinationHttpClientConfiguration$$SpringCGLIB$$0.requestFactory(<generated>) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:146) ~[spring-beans-6.1.13.jar:6.1.13]
	... 21 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.hc.client5.http.ssl.TlsSocketStrategy
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 46 common frames omitted
```

## Relevant code

```
@Configuration
class SapDestinationHttpClientConfiguration {

    @Bean
    HttpComponentsClientHttpRequestFactory requestFactory() {
        Destination destination = DestinationAccessor.getDestination("DESTINATION_DEV")
        HttpClient client = ApacheHttpClient5Accessor.getHttpClient(destination)
        return new HttpComponentsClientHttpRequestFactory(client)
    }

}
```

## Complete source code
https://github.com/gsartori/sap-httpclient

## To reproduce the issue
`./gradlew bootRun`

**Comment by gsartori** [comment]
@MatKuhr in the meantime I did exactly what you are suggesting, I now have the following issue (I've updated the test app on git to match this new scenario)

```
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.apache.hc.client5.http.impl.io.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:86)

The following method did not exist:

    'void org.apache.hc.core5.http.impl.io.DefaultHttpRequestWriterFactory.<init>(org.apache.hc.core5.http.config.Http1Config)'

The calling method's class, org.apache.hc.client5.http.impl.io.ManagedHttpClientConnectionFactory, was loaded from the following location:

    jar:file:/Users/giangio/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents.client5/httpclient5/5.4/8f5efeb3af5b5196925ea20d25c052ec9ac24d63/httpclient5-5.4.jar!/org/apache/hc/client5/http/impl/io/ManagedHttpClientConnectionFactory.class

The called method's class, org.apache.hc.core5.http.impl.io.DefaultHttpRequestWriterFactory, is available from the following locations:

    jar:file:/Users/giangio/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents.core5/httpcore5/5.2.5/dab1e18842971a45ca8942491ce005ab86a028d7/httpcore5-5.2.5.jar!/org/apache/hc/core5/http/impl/io/DefaultHttpRequestWriterFactory.class

The called method's class hierarchy was loaded from the following locations:

    org.apache.hc.core5.http.impl.io.DefaultHttpRequestWriterFactory: file:/Users/giangio/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents.core5/httpcore5/5.2.5/dab1e18842971a45ca8942491ce005ab86a028d7/httpcore5-5.2.5.jar


Action:

Correct the classpath of your application so that it contains compatible versions of the classes org.apache.hc.client5.http.impl.io.ManagedHttpClientConnectionFactory and org.apache.hc.core5.http.impl.io.DefaultHttpRequestWriterFactory
```

It looks like it's a bug in the Apache code in class `ManagedHttpClientConnectionFactory` at line `86` they are calling a constructor with a wrong parameter type (??). I am not sure about that cause it whouldn't have compiled but this is what I am seeing in the downloaded sources:

## Code @ `ManagedHttpClientConnectionFactory` line `86`
```
        this.requestWriterFactory = requestWriterFactory != null ? requestWriterFactory :
                new DefaultHttpRequestWriterFactory(this.h1Config);
```

## Constructor

```
    public DefaultHttpRequestWriterFactory(LineFormatter lineFormatter) {
        this.lineFormatter = (LineFormatter)(lineFormatter != null ? lineFormatter : BasicLineFormatter.INSTANCE);
    }
```

I'm opening an issue on their side as well.

**Comment by MatKuhr** [comment]
Sorry, I should have added: Please also use version 5.3 of https://central.sonatype.com/artifact/org.apache.httpcomponents.core5/httpcore5 as well. The two go together more or less 😅

When you use our BOM correctly this should also be made consistent through the BOM.

**Comment by gsartori** [comment]
Thank you for the hint! I will stay on `5.12.0` for the moment, I don't like messing up with dependencies :)

**Comment by sippnex** [comment]
In my case the problem was the version of Spring Boot. Spring Boot also includes the Apache httpclient5 dependency (via "spring-boot-dependencies" pom.xml).
I increased the Spring Boot Parent version from 3.3.0 to 3.5.0. After that, everything worked fine.
